Push and pull use cases
GCDTech/Module.Cyclops pull request #1
Opened 2018-10-01 10:48 UTC by catherineGCD

For tasks:
* https://www.pivotaltracker.com/story/show/160486366
* https://www.pivotaltracker.com/story/show/160487450
* https://www.pivotaltracker.com/story/show/160487554
* https://www.pivotaltracker.com/story/show/160487537

2018-10-01 14:02 UTC, samnotsowise commented
a wee `Readme.md` in the project root explaining the use of these use cases and any caveats/things to be mindful of would be great. Also, tests

2018-10-02 08:32 UTC, samnotsowise commented on src/UseCases/PullChangesFromCyclopsUseCase.php
> +            if (file_exists('/cyclops/last-status-changes-date.txt')) {
i wouldn't do any of this in the use case. This is all environment specific storage and retrieval, I'd suggest that the command could do this (but not in the root directory, work relative to the working directory). In my opinion the use cae should just get in a `\DateTime` object and return a `\DateTime`, which the command can take care of storing and providing each time.

2018-10-02 09:00 UTC, catherineGCD commented
@samnotsowise all updated, I'll do the writing to file in the command which will be a later PR!

2018-10-02 15:01 UTC, CerzBbz approved these changes

2018-10-02 15:17 UTC, CerzBbz commented on src/UseCases/PushStaleToCyclopsUseCase.php
> +            } catch (CyclopsException $exception) {
Why are we catching it if we're not going to handle it? Same with **PushDeletedToCyclopsUseCase.php:26**

2018-10-02 15:20 UTC, CerzBbz commented on src/UseCases/PushStaleToCyclopsUseCase.php
> +            } catch (CyclopsException $exception) {
Also if you're getting Forbidden/CustomerNotFound there's no point continuing the **Foreach** because nothing else will be processed anyway.

2018-10-02 15:25 UTC, CerzBbz requested changes
Comments around exception handling when pushing/deleting brand opt in & subscription values

2018-10-03 15:01 UTC, CerzBbz approved these changes

2018-10-19 15:37 UTC, merged